joint_state_publisher_gui:
  ros__parameters:
    link1:
      a: 3
      d: 0
      alpha: 0
      theta: 0
    link2:
      a: 3
      d: 0
      alpha: 1.57075
      theta: 0
    link3:
      a: 3
      d: 0
      alpha: 0
      theta: 0